### ISSUE TITLE
How to use the proejct?

### ISSUE THREAD

**Issue by xx7Ahmed7xx** [PhilippThoelke/protein-folding#2]
Can you kindly provide example of how to use this project? Like input example to start and steps to run and finally output?
Thanks in advance.

**Comment by dav0dea** [comment]
Hi, this project was merely a collection of experiments I made some time ago. Nothing here is finished or up-to-date, it's basically just a sandbox with some ideas. If you're interested in protein folding and machine learning aided simulation, I suggest looking [ACEMD](https://www.acellera.com/acemd/) or [OpenMM](https://openmm.org/) with [OpenMM-Torch](https://github.com/openmm/openmm-torch) for a PyTorch integration. There is some promising work on neural network force fields for proteins.

**Comment by xx7Ahmed7xx** [comment]
Okay I just want to get a prediction of my amino acids sequence to protein, Can you maybe provide a small direction or steps to follow?

**Comment by dav0dea** [comment]
This is by no means a trivial task and has still not a fully solved, unless you have A LOT of compute and time. I guess if you just want the structure from an AA sequence, AlphaFold is the best shot with reasonable time and resources. There are Google Colab implementations, which as far as I know can predict the structure based on the primary sequence. I don't have a link to any though.
